/**
 * 테마별 Playground 색상 정의
 */

export const playgroundColors = {
  dark: {
    pageBg: '#0a0f1a',
    panelBg: '#0d1525',
    headerBg: '#0d1525',
    border: '#1a2540',
    resizeHandle: '#1a2d4a',
    resizeHover: '#2a3d5a',
    text: '#e8f0ff',
    textMuted: '#b8c8e8',
    textDim: '#8ba3cf',
    accent: '#00ffff',
    accentBg: '#0a2040',
    accentBorder: '#00aaff',
    explanationBg: '#081820',
    explanationHeaderBg: '#0a2540',
    explanationBorder: '#00aaff',
    explanationText: '#00ffff',
    explanationTextMuted: '#00ddff',
    errorBg: '#180810',
    errorBorder: '#ff3366',
    errorText: '#ff5577',
    footerBg: '#080d18',
    footerBorder: '#1a2540',
    footerText: '#b8c8e8',
  },
  soft: {
    pageBg: '#faf8fc',
    panelBg: '#ffffff',
    headerBg: '#ffffff',
    border: '#ebe4ed',
    resizeHandle: '#e9d5ff',
    resizeHover: '#d8b4fe',
    text: '#6b5a7a',
    textMuted: '#a08eb0',
    textDim: '#c4b5d0',
    accent: '#a855f7',
    accentBg: '#faf5ff',
    accentBorder: '#e9d5ff',
    explanationBg: '#f0fdf4',
    explanationHeaderBg: '#dcfce7',
    explanationBorder: '#bbf7d0',
    explanationText: '#166534',
    explanationTextMuted: '#16a34a',
    errorBg: '#fef2f2',
    errorBorder: '#fecaca',
    errorText: '#dc2626',
    footerBg: '#f3eef8',
    footerBorder: '#ebe4ed',
    footerText: '#a08eb0',
  },
  minimal: {
    pageBg: '#faf9f7',
    panelBg: '#fffffe',
    headerBg: '#fffffe',
    border: '#e5d5c7',
    resizeHandle: '#d6cfc5',
    resizeHover: '#c4b8a8',
    text: '#5c4a3d',
    textMuted: '#8a8279',
    textDim: '#a39585',
    accent: '#a08060',
    accentBg: '#fef3c7',
    accentBorder: '#fcd34d',
    explanationBg: '#fefce8',
    explanationHeaderBg: '#fef9c3',
    explanationBorder: '#fde047',
    explanationText: '#854d0e',
    explanationTextMuted: '#a16207',
    errorBg: '#fef2f2',
    errorBorder: '#fecaca',
    errorText: '#dc2626',
    footerBg: '#f5f3f0',
    footerBorder: '#e5d5c7',
    footerText: '#8a8279',
  },
} as const;

export type PlaygroundTheme = (typeof playgroundColors)[keyof typeof playgroundColors];
